# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_clothing_clothing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='clothing_type',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
